"""message model

Revision ID: 22a7b0c95f08
Revises: 
Create Date: 2024-12-11 21:20:07.907561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a7b0c95f08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'message', 'users', ['receiver_id'], ['user_id'])
    op.create_foreign_key(None, 'message', 'users', ['sender_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'is_read')
    op.drop_column('message', 'timestamp')
    op.drop_column('message', 'content')
    op.drop_column('message', 'receiver_id')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
