"""Global message table

Revision ID: 680f3ef7a818
Revises: 304e52872816
Create Date: 2024-12-18 12:08:38.713270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680f3ef7a818'
down_revision: Union[str, None] = '304e52872816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_receiver_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_receiver_id_fkey', 'message', 'users', ['receiver_id'], ['user_id'])
    # ### end Alembic commands ###
